{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  BETTER_AUTH_SECRET: {{ .Values.backend.secrets.betterAuthSecret | quote }}
  SECRET_KEY: {{ .Values.backend.secrets.secretKey | quote }}
  GROQ_API_KEY: {{ .Values.backend.secrets.groqApiKey | quote }}
{{- end }}
