{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-postgres-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
